package davidebraghi.CapstoneProject_TimelineManager.Payload_DTO.RoleChange_DTO_RequestsAndResponses;

import davidebraghi.CapstoneProject_TimelineManager.enums.RoleNameENUM;

public record RoleChangeRequest(RoleNameENUM newRole) {
}